// app/types.ts
export interface Product {
    id: string;
    name: string;
    cost: number;
    image: string;
    description: string;
}

export interface CartItem extends Product {
    quantity: number;
}

export interface OrderItem {
    id: string;
    name: string;
    cost: number;
    quantity: number;
}

export interface Order {
    id?: string; // UUID generated by DB
    checkoutCode: string;
    items: OrderItem[]; // Stored as JSONB
    totalCost: number;
    orderDate?: string; // ISO date string
}